language: node_js
node_js:
  - 'v10.9.0'
cache:
  directories:
    - node_modules
    - '$HOME/.npm'
install:
  - npm ci
script:
  - npm run lint
  - npm run tsc
  - npm run test:ci
  - npm run type-coverage
